pipeline {
    agent any

    stages {
        stage('Initialize') {
            steps {
                echo '🚀 Démarrage du Pipeline...'
                // IMPORTANT : On entre dans le dossier où se trouve le pom.xml
                dir('todo-app') {
                    // On donne les droits d'exécution au wrapper
                    sh 'chmod +x mvnw'
                    sh './mvnw -version'
                }
            }
        }

        stage('Build & Test') {
            steps {
                dir('todo-app') {
                    echo '🧪 Lancement des Tests et de JaCoCo...'
                    // Lancement via le wrapper (plus sûr que 'mvn')
                    sh './mvnw clean verify'
                }
            }
        }
    }

    post {
        always {
            dir('todo-app') {
                echo '📝 Récupération des rapports...'
                junit 'target/surefire-reports/*.xml'
                
                publishHTML (target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/site/jacoco',
                    reportFiles: 'index.html',
                    reportName: 'Rapport Couverture Code'
                ])
            }
        }
        success {
            echo '✅ SUCCÈS : Projet validé !'
        }
        failure {
            echo '❌ ÉCHEC : Regardez les logs pour voir l\'erreur.'
        }
    }
}